---
language: python
python: "3.7"
sudo: required
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - DOCKER_IMAGE_BASE=idealista/jdk:8u252-stretch-openjdk-headless
    - DOCKER_IMAGE_BASE=idealista/jdk:11.0.7-buster-openjdk-headless
    - DOCKER_IMAGE_BASE=idealista/jdk:11.0.6-stretch-openjdk-headless
    - DOCKER_IMAGE_BASE=idealista/jdk:8u252-focal-openjdk-headless
    - DOCKER_IMAGE_BASE=idealista/jdk:14.0.1-focal-openjdk-headless
script:
  - pipenv run molecule test --all --destroy always

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
