---
language: python
python: "2.7.13"
sudo: required
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
script:
  - pipenv shell
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
