---

- name: SolrCloud | Give execution permission to zkcli script
  file:
    path: "{{ zookeeper_client_path }}/zkcli.sh"
    mode: 0744

- name: SolrCloud | Create Root Path (znode) in ZooKeeper using zkcli script
  shell: "{{ zookeeper_client_path }}/zkcli.sh -zkhost {{ zookeeper_hosts }} -cmd makepath /{{ zookeeper_hosts_solr_path }} >> /tmp/path_created.out"
  args:
    creates: /tmp/path_created.out
  ignore_errors: true
  tags:
   skip_ansible_lint

- name: SolrCloud | Configuring jetty server
  template:
      src: jetty.xml.j2
      dest: /opt/solr/server/etc/jetty.xml
      force: yes
  notify: restart SolrCloud

- name: SolrCloud | Configuring jetty server http
  template:
      src: jetty-http.xml.j2
      dest: /opt/solr/server/etc/jetty-http.xml
      force: yes
  notify: restart SolrCloud

- name: SolrCloud | Configuring SolrCloud init script
  template:
      src: solr.in.sh.j2
      dest: /etc/default/solr.in.sh
      force: yes
  notify: restart SolrCloud

- name: SolrCloud | Configuring SolrCloud properties
  template:
      src: solr.xml.j2
      dest: "{{ solr_data_dir }}/solr.xml"
      force: yes
  notify: restart SolrCloud

- name: SolrCloud | Configuring logging
  template:
      src: log4j.properties.j2
      dest: /opt/solr/log4j.properties
      force: yes
  notify: restart SolrCloud

- name: SolrCloud | Create NFS folder (Install dependencies)
  apt:
    name: nfs-common
    state: installed
  when: mount_name is defined and mount_source is defined

- name: SolrCloud | Create NFS folder (Mount the folder)
  mount:
    name: "{{ mount_name }}"
    src: "{{ mount_source }}"
    fstype: nfs
    opts: "{{ mount_options }}"
    state: mounted
  when: mount_name is defined and mount_source is defined

- name: SolrCloud | Create NFS folder (Change owner)
  file:
    path: "{{ mount_name }}"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_group }}"
  when: mount_name is defined and mount_source is defined
