---

- name: SolrCloud | Install
  include: install.yml
  tags:
    - install

- name: SolrCloud | Configure
  include: config.yml
  tags:
    - configure

- name: SolrCloud | Service
  include: service.yml
  tags:
    - service

- name: SolrCloud | Manage collections
  include: collections.yml
  run_once: true
  tags:
    - collections
