---

- name: Solr | Prepare env
  import_tasks: reinstall.yml
  tags:
    - solr_install
  when: solr_force_reinstall

- name: Solr | Install
  import_tasks: install.yml
  tags:
    - solr_install

- name: Solr | OS Tunning
  import_tasks: os-tunning.yml
  tags:
    - solr_tunning
  when: solr_os_tunning

- name: Solr | Agent config
  import_tasks: agent.yml
  tags:
    - solr_agent_config
  when: solr_agents_config is defined

- name: Solr | Configure cloud
  import_tasks: config-cloud.yml
  when: solr_mode == 'cloud'
  tags:
    - configure

- name: Solr | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: Solr | Cleanup
  import_tasks: cleanup.yml
  tags:
    - solr_cleanup
  when: solr_cleanup

- name: Solr | Service
  import_tasks: service.yml
  tags:
    - solr_service

- name: Solr | Manage packages
  import_tasks: packages.yml
  when: solr_external_packages is defined and solr_external_packages|length > 0 and solr_mode == 'cloud'
  run_once: true
  tags:
    - solr_packages

- name: Solr | Manage collections
  import_tasks: collections.yml
  when: solr_collections is defined and solr_collections|length > 0 and solr_mode == 'cloud' and ansible_play_hosts_all|length > 0 and inventory_hostname == ansible_play_hosts_all[0]
  run_once: true
  tags:
    - solr_collections

- name: Solr | Manage cores
  import_tasks: cores.yml
  when: solr_cores is defined and solr_cores|length > 0 and solr_mode == 'standalone'
  run_once: true
  tags:
    - solr_cores
