---

- name: SolrCloud | Install
  import_tasks: install.yml
  tags:
    - install

- name: SolrCloud | Agent config
  import_tasks: agent.yml
  tags:
    - solr_agent_config
  when: solr_agents_config is defined

- name: SolrCloud | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: SolrCloud | Service
  import_tasks: service.yml
  tags:
    - service

- name: SolrCloud | Manage collections
  import_tasks: collections.yml
  when: solr_collections is defined and solr_collections|length > 0
  run_once: true
  tags:
    - collections
