---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: zookeeper
    image: geerlingguy/docker-debian9-ansible
    image_version: latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - zookeeper_group
    command: '/lib/systemd/systemd'
    networks:
      - name: solr-network
        aliases:
          - zookeeper
  - name: solrcloud
    image: geerlingguy/docker-debian9-ansible
    image_version: latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - solrcloud_group
    command: '/lib/systemd/systemd'
    networks:
      - name: solr-network
        aliases:
          - solrcloud
        links:
          - zookeeper:zookeeper
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
