---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: zookeeper
    hostname: zookeeper
    groups:
      - zookeeper_group
    image: geerlingguy/docker-debian9-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
  - name: solrcloud
    hostname: solrcloud
    groups:
      - solrcloud_group
    image: geerlingguy/docker-debian9-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    links:
      zookeeper: zookeeper
    command: '/lib/systemd/systemd'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
